-- AlterTable
ALTER TABLE "public.patients" ALTER COLUMN "phone_number" DROP NOT NULL,
ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "cpf" DROP NOT NULL,
ALTER COLUMN "birth_day" DROP NOT NULL,
ALTER COLUMN "address" DROP NOT NULL;
